### ISSUE TITLE
Bed doesn't move away once print is complete

### ISSUE THREAD

**Issue by kanishk619** [K1-Klipper/cartographer-klipper#14]
Once the print is finished, the only moves away 5mm from nozzle making it hard to remove the print plate. I had to home XY and then manually lower Z. 

Calling END_PRINT_POINT fixes this issue.

<pre>
[gcode_macro END_PRINT]
gcode:
  # Qmode_exit
  G91                                                                                 # set to reletive positioning
  G1 Z5                                                                               # move z down 5mm to avoid contacting nozzle
  G90                                                                                 # set to absolute positioning
  {% set POSITION_X = printer.configfile.settings['stepper_x'].position_max *0.99 %}  # Calculate 99% position of X 
  {% set POSITION_Y = printer.configfile.settings['stepper_y'].position_max /2 %}     # calculate 50% of total Y
  G1 X{POSITION_X} Y{POSITION_Y} F6000                                                # move toolhead to the front of the K1 aux fan like stock
  M220 S100                                                                           # set feedrate to 100
  M204 S500                                                                           # set starting acceleration to 500
  TURN_OFF_HEATERS                                                                    # disable heaters
  M107 P1                                                                             # turn toolehad fan off
  M107 P2                                                                             # turn sidefan off
  END_PRINT_POINT                                                                     # this moves bed away to middle
  M84                                                                                 # power off motors
    {action_respond_info("Print complete!")}                                          # End Print Notification
</pre>

**Comment by shimakazevr** [comment]
this was set like this to allow for some compatibility with people board-swapping to manta series.

The bed does lower slightly (5mm) before doing a travel move to park the toolhead to avoid hitting the print while also preventing the bed from crashing when its at the maximum z travel in slicer. theres really no need to drop the print bed so far down unless you're trying to retain the stock behaviour with shorter prints which you can do like shown in this gcode.

i will add this line commented with a short description for those that wish to do this ^^
