### ISSUE TITLE
Unknown command:"_SMART_PARK" and "_LINE_PURGE"

### ISSUE THREAD

**Issue by kanishk619** [K1-Klipper/cartographer-klipper#15]
I followed the cartographer guide which installs KAMP and required macros. However, upon using PRINT_START, got the following errors

> Unknown command:"_SMART_PARK"
> Unknown command:"_LINE_PURGE"

In PRINT_START macro, changing _SMART_PARK to SMART_PARK and _LINE_PURGE to LINE_PURGE fixes the issue

**Comment by shimakazevr** [comment]
looking at the current helper script version supplied by Guilouz, the macro's being called are correct?


https://github.com/Guilouz/Creality-Helper-Script/blob/main/files/kamp/Line_Purge.cfg   (line 5)

https://github.com/Guilouz/Creality-Helper-Script/blob/main/files/kamp/Smart_Park.cfg   (line 5)
