### ISSUE TITLE
Cartographer_macro.cfg K1 Max

### ISSUE THREAD

**Issue by cavo14** [K1-Klipper/cartographer-klipper#9]
cam_start command doesn't seem to work to restart the camera. Once cam_stop is issued the only way to get the camera to work again is to power cycle the printer. 

The only thing I can think of that may be causing this is that I disabled all creality services when installing guppyscreen. I also uninstalled creality webservices using the Helper Script by Guilouz. But I believe this is what is recommended on the cartographer webpage for k1 and k1 max.

I also use Moonraker to set my webcam settings if that can cause any of this.

I did check if I could disable the cam_stop and cam-start commands and bed mesh definitely crashes the mcu without disabling the camera. 

I did try installing mjpg-streamer from entware and changed the location of opt/lib to usr/lib but still no dice. 

I also tried deleting killall mjpg_streamer, killall cx_ai_middleware and killall cam_app one by one and that didn't fix it or make the problem go away.

**Comment by sbtoonz** [comment]
this indicates entware fails to install

**Comment by sbtoonz** [comment]
@cavo14 


https://github.com/K1-Klipper/cartographer-klipper/commit/de7be59a0683796b74471abda94f56d153af79af

This SHOULD have fixed that issue

have you attempted to re install since this change?

**Comment by cavo14** [comment]
Yep that seems to have fixed it. All I have to do now on my side is refresh fluidd in my browser after the camera resets.
